title: hidakatsuya.dev
description: Tech and life logs, my profile, etc

baseurl: ""
url: "https://hidakatsuya.dev"

timezone: Asia/Tokyo

remote_theme: pages-themes/primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-gist
  - jemoji

google_analytics: G-RR4D3YF2FY

relative_links:
  collections: true

gist:
  noscript: false

twitter:
  username: hidakatsuya
  card: summary

markdown: CommonMarkGhPages
commonmark:
  options:
    - UNSAFE
  extensions:
    - autolink
    - strikethrough
    - table

defaults:
  - scope:
      path: ""
    values:
      layout: post
